services:
  # Servicio de Base de Datos
  db:
    image: postgres:15
    container_name: nexgen_db
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contra123
      POSTGRES_DB: control_escolar_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build: ./backend
    container_name: nexgen_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db 
      - DB_USER=usuario
      - DB_PASSWORD=contra123
      - DB_NAME=control_escolar_db
      - JWT_SECRET=super_secreto
    depends_on:
      - db

  client:
    build: ./frontend
    container_name: nexgen_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - api

volumes:
  postgres_data: